In [9]:
import yaml
import pickle

In [10]:
config_file = "../config_multiscope/dot_multi_vpn_scale5k10k.yaml"
with open(config_file, 'r') as file:
    config = yaml.safe_load(file)

In [11]:
p_filename = "../" + config['experiment_name'] + "_ts.pkl"

with open(p_filename, 'rb') as file:
    src = pickle.load(file)
    dst = pickle.load(file)

In [12]:
dst['/tordata/config/group_0_user_0']

                         text_len  count
time
2025-05-07 11:08:42.654        86      1
2025-05-07 11:08:45.987      1381      5
2025-05-07 11:08:49.320       892      3
2025-05-07 11:08:52.653       834      2
2025-05-07 11:08:55.986         0      0
...                           ...    ...
2025-05-07 12:53:12.027         0      0
2025-05-07 12:53:15.360         0      0
2025-05-07 12:53:18.693         0      0
2025-05-07 12:53:22.026         0      0
2025-05-07 12:53:25.359       275      1

[1886 rows x 2 columns]

In [13]:
src['102.0.0.10']

,ip.len,tcp.dstport,tcp.ack,tcp.len,tcp.reassembled.length,tcp.time_relative,tcp.time_delta,count,ip.len_ISP1-all,tcp.dstport_ISP1-all,...,tcp.time_delta_Service-2,count_Service-2,ip.len_Service-3,tcp.dstport_Service-3,tcp.ack_Service-3,tcp.len_Service-3,tcp.time_relative_Service-3,tcp.time_delta_Service-3,count_Service-3,frame.time
frame.time,,,,,,,,,,,,,,,,,,,,,
2025-05-07 11:02:22.692,0.0,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 11:02:22.692
2025-05-07 11:02:26.025,0.0,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 11:02:26.025
2025-05-07 11:02:29.358,0.0,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 11:02:29.358
2025-05-07 11:02:32.691,0.0,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 11:02:32.691
2025-05-07 11:02:36.024,0.0,0.0,0.000000e+00,0.0,0.0,0.000000,0.000000,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 11:02:36.024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-05-07 13:07:15.276,48174.0,5537214.0,6.076309e+09,34726.0,414.0,30940.861775,7701.097852,256.0,16133.0,1889975.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 13:07:15.276
2025-05-07 13:07:18.609,6258.0,243136.0,1.800000e+01,5170.0,0.0,25.710770,8.345646,20.0,3129.0,121568.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 13:07:18.609
2025-05-07 13:07:21.942,46764.0,5668570.0,1.750070e+05,33620.0,0.0,185.461075,19.663837,250.0,15486.0,1772017.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 13:07:21.942
2025-05-07 13:07:25.275,50546.0,5194092.0,1.527244e+11,36762.0,414.0,281621.183445,34661.125352,264.0,17287.0,1581275.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 13:07:25.275
2025-05-07 13:07:28.608,32484.0,2844860.0,4.086340e+10,24636.0,0.0,166664.076331,24690.923332,150.0,12321.0,1021414.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2025-05-07 13:07:28.608

In [35]:
import pandas as pd 

def ts2nccvec(ts: pd.core.frame.DataFrame):
    sample_offset = ((len(ts)-1)**0.5)
    return (ts - ts.mean()) / (ts.std()*sample_offset)
    
vec = ts2nccvec(dst['/tordata/config/group_0_user_0']["text_len"])
vec

time
2025-05-07 11:08:42.654    0.010454
2025-05-07 11:08:45.987    0.221625
2025-05-07 11:08:49.320    0.141886
2025-05-07 11:08:52.653    0.132428
2025-05-07 11:08:55.986   -0.003570
                             ...
2025-05-07 12:53:12.027   -0.003570
2025-05-07 12:53:15.360   -0.003570
2025-05-07 12:53:18.693   -0.003570
2025-05-07 12:53:22.026   -0.003570
2025-05-07 12:53:25.359    0.041274
Name: text_len, Length: 1886, dtype: float64

In [36]:
import numpy as np
np.dot(vec.to_numpy(), vec.to_numpy())

0.999999999999999

### Todo
- **Find way to align dataset**
    - chunk, fill zeros, etc
    - _Last big thing to do before all out test of method_
- Get end to end working
    - Send pcaps dfs through ncc GIS stuff
- Run new experiment loop
    - run through all features/combos and report metrics

In [62]:
scale_factor = 300
chunk_size = td = pd.Timedelta(1, "W")/scale_factor
chunk_size

Timedelta('0 days 00:33:36')

In [63]:
start = min([src[ip].index[0] for ip in src])
start

Timestamp('2025-05-07 11:02:22.692000')

In [134]:
# Fill zeros in missing indexes
full_index = pd.Index([])

for ip in src:
    full_index = full_index.union(src[ip].index)
    
for user in dst:
    full_index = full_index.union(dst[user].index)

for ip in src:
    src[ip] = src[ip].reindex(full_index, fill_value=0)

for user in dst:
    dst[user] = dst[user].reindex(full_index, fill_value=0)

In [135]:
src_chunks = {}

for ip in src:
    cur = start
    end = src[ip].index[-1]
    src_chunks[ip] = {}
    
    while cur < end:
        src_chunks[ip][cur] = src[ip][cur:cur+chunk_size]
        cur += chunk_size

dst_chunks = {}

for user in dst:
    cur = start
    end = dst[user].index[-1]
    dst_chunks[user] = {}
    
    while cur < end:
        dst_chunks[user][cur] = dst[user][cur:cur+chunk_size]
        cur += chunk_size

In [136]:
# - fill out zeros in the other timestamps for smaller chunks (could do this before or after chunking)
# - copy NCCTree class over
# - Send through as test (def eval(src_chunks[f], dst_chunks[f], label_func) -> List[Metrics] )
# - Setup experiment full loop (loop over all feature combos and multithread, save out to a file)

In [140]:
dst_chunks['/tordata/config/group_0_user_0'][pd.Timestamp('2025-05-07 11:02:22.692000')]

                         text_len  count
2025-05-07 11:02:22.692         0      0
2025-05-07 11:02:26.025         0      0
2025-05-07 11:02:29.358         0      0
2025-05-07 11:02:32.691         0      0
2025-05-07 11:02:36.024         0      0
...                           ...    ...
2025-05-07 11:35:42.492         0      0
2025-05-07 11:35:45.825         0      0
2025-05-07 11:35:49.158         0      0
2025-05-07 11:35:52.491         0      0
2025-05-07 11:35:55.824         0      0

[605 rows x 2 columns]